server:
  port: 8080
  reactive:
    session:
      # must be same value like SSO Session Idle in keycloak
      timeout: 6m

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    root: debug

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/GISTest
            user-name-attribute: preferred_username
        registration:
          gis:
            provider: keycloak
            client-id: gis
            client-secret: 9HgEFtNJTejsk9O4S3hdX7lC8K8fU0Ot
            # to provide after login redirects we need this grant type
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
            # to provide logout we need this scope
            scope: openid
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 600s
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: analytics
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/analytics-service/**
        - id: dictionary
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/dictionary-service/**

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
